### ISSUE TITLE
🐛Permission issue misleading

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/VersionMiner#143]
### Complete The Items Below

- [X] I have updated the title without removing the 🐛 emoji.
- [X] I searched whether or not an issue already exists for the bug I encountered.

### Current Behavior

When running the action, it reports that the repository does not exist and the action does not fail.

Some research showed that the repository does exist but the reason for the error message was because the secret used did not exist so the action did not have permissions.  This is a permission issue.  The problem is that the error message is not reporting correctly that it IS a permission issue.  It is also not failing the job like it should.

> **Note** This was discovered while debugging the preview release workflow implementation for the following issue:
> - KinsonDigital/CASL#215

### Expected Behavior

When the repository does not exist, the workflow should fail.

### Steps To Reproduce

1. Provide a repo to the action that does not exist
2. Run the workflow to run the action
3. Observe that the step/job passes instead of failing.

### Operating System(s)

- [X] Windows
- [X] Linux
- [X] Android
- [X] Mac OS
- [X] iOS
- [x] Other

### OS Version

v1.0.0-preview.4

### Anything Else

Here is the input data that was used in the action:
```yml
  with:
    repo-owner: KinsonDigital
    repo-name: CICD
    repo-token: ***
    branch-name: feature/215-create-release-workflow
    file-format: xml
    file-path: CASL/CASL.csproj
    version-keys: Version
    case-sensitive-keys: true
    fail-on-key-value-mismatch: false
    fail-when-version-not-found: true
  env:
    PROJECT_NAME: CASL
```

**ScreenShot:**
<img width="906" alt="image" src="https://github.com/KinsonDigital/VersionMiner/assets/96791049/0c3d217d-8e72-44e9-a2e3-df5578df6828">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
