### ISSUE TITLE
Change action icon for marketplace

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#28]
### **Description:**
Change the icon for the GitHub action marketplace from **purple settings** to **purple search**

```yml
name: 'Version Miner'
description: 'Pulls versions out from various types of files.'
author: 'Calvin Wilkinson (KinsonDigital)'
branding:
  icon: settings 👈🏼 Change to "search"
  color: purple
inputs:
```

### **Acceptance Criteria:**
- [x] Icon changed
